//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp.entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class CARD
    {
        public long CARDCODE { get; set; }
        public Nullable<System.DateTime> STARTDATE { get; set; }
        public Nullable<System.DateTime> FINISHDATE { get; set; }
        public string LASTNAME { get; set; }
        public string FIRSTNAME { get; set; }
        public string SURNAME { get; set; }
        public string FULLNAME { get; set; }
        public Nullable<int> GENDERID { get; set; }
        public Nullable<System.DateTime> BIRTHDAY { get; set; }
        public string PHONEHOME { get; set; }
        public string PHONEMOBIL { get; set; }
        public string EMAIL { get; set; }
        public string CITY { get; set; }
        public string STREET { get; set; }
        public Nullable<int> HOUSE { get; set; }
        public Nullable<int> APARTMENT { get; set; }
        public string ALTADDRESS { get; set; }
        public string CARDTYPE { get; set; }
        public System.Guid OWNERGUID { get; set; }
        public int CARDPER { get; set; }
        public Nullable<decimal> TURNOVER { get; set; }
    
        public virtual Gender Gender { get; set; }
    }
}
